
# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Theme settings
doks:
    baseurl:
    color_theme: yellow
    header:
        logo:
            text: andrews.house
            image:
        nav:
            - item_name: Item 1
              item_url: '#'
            - item_name: Item 2
              item_url: '#'
            - item_name: Item 3
              item_url: '#'
    footer:
        content:
            logo:
                text: andrews.house
                image:
            copyright: Copyright &copy; 2018. - andrews.house <br>All rights reserved.
        social_list:
            - network_name: facebook
              profile_url: 'https://facebook.com/mortocks'
            - network_name: twitter
              profile_url: 'https://twitter.com/mortocks'
            - network_name: instagram
              profile_url: 'https://www.instagram.com/mortocks/'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/


plugins:
  - jekyll-paginate
